import type { Metadata } from "next";
import "./globals.css";
import SessionWrapper from "./components/SessionWrapper";
import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <SessionWrapper>
        <body className="flex flex-col min-h-screen">
          <Header />
          <main className="flex-grow container flex flex-col gap-24 md:gap-32 mx-auto px-4 md:px-6 lg:px-20  py-16 md:py-20">
            {children}
          </main>
          <Footer />
        </body>
      </SessionWrapper>
    </html>
  );
}